version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - frontend
    depends_on:
      - flask

  flask:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      MONGO_URL: mongodb://admin:password@mongodb:27017/db?authSource=db
      FLASK_ENV: production
      HOST: '0.0.0.0'
      DEBUG: 'false'
    networks:
      - frontend
      - backend
    depends_on:
      - mongodb

  mongodb:
    image: bitnami/mongodb:5.0.4
    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: db      
      MONGODB_ROOT_PASSWORD: root
    networks:
      - backend

networks:
  frontend:
  backend: