version: '3'

services:
  nginx:
    image: 498047829710.dkr.ecr.eu-central-1.amazonaws.com/todolistnginx:${NGINX_VER}
    ports:
      - 80:80
    depends_on:
      - flask

  flask:
    image: 498047829710.dkr.ecr.eu-central-1.amazonaws.com/todolistapp:${APPLICATION_VER}
    environment:
      MONGO_URL: mongodb://admin:password@mongodb:27017/db?authSource=db
      FLASK_ENV: production
      HOST: '0.0.0.0'
      DEBUG: 'false'
    depends_on:
      - mongodb

  mongodb:
    image: bitnami/mongodb:5.0.4
    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: db      
      MONGODB_ROOT_PASSWORD: root