version: '3'

services:
  nginx:
    image: 006262944085.dkr.ecr.eu-west-2.amazonaws.com/todolistnginx:${NGINX_VER}
    ports:
      - 80:80
    volumes:
      - /home/ec2-user/jenkins/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask

  flask:
    image: 006262944085.dkr.ecr.eu-west-2.amazonaws.com/todolistapp:${APPLICATION_VER}
    environment:
      MONGO_URL: mongodb://admin:password@mongodb:27017/db?authSource=db
      FLASK_ENV: production
      HOST: '0.0.0.0'
      DEBUG: 'false'
    depends_on:
      - mongodb

  mongodb:
    image: bitnami/mongodb:5.0.4
    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: db      
      MONGODB_ROOT_PASSWORD: 123456789